main_window_stylesheet = ("    background-color: rgb(17, 18, 17);\n"
"    border-radius:10px;\n"
"    border-style:solid;\n")
title_bar_frame_stylesheet_window_normal = ("    background-color: rgb(17, 18, 17);\n"
"    border-top-left-radius:10px;\n"
"    border-top-right-radius:10px;\n"
"    border-style:solid;\n")
title_bar_frame_stylesheet_window_maximized = ("    background-color: rgb(17, 18, 17);\n"
"    border-top-left-radius:0px;\n"
"    border-top-right-radius:10px;\n"
"    border-style:solid;\n")
deco_button_stylesheet = ("background-color: qlineargradient(spread:reflect, x1:0, y1:0.0170455, x2:1, y2:0, stop:0 rgba(25, 26, 25, 255), stop:1 rgba(17, 18, 17, 255));\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:0px;")
minimize_button_stylesheet = ("QPushButton {\n"
"    background-color: rgb(17, 18, 17);\n"
"    border-radius:0px;\n"
"    margin:0px;   \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(50, 51, 50);\n"
"    border-radius:0px;\n"
"    border-color:none;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(37, 38, 37);\n"
"    border-radius:0px;\n"
"}\n"
"")
maximize_button_stylesheet = ("QPushButton {\n"
"    background-color: rgb(17, 18, 17);\n"
"    border-radius:0px;\n"
"    margin:0px;   \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(50, 51, 50);\n"
"    border-radius:0px;\n"
"    border-color:none;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(37, 38, 37);\n"
"    border-radius:0px;\n"
"}\n"
"")
exit_button_stylesheet_window_normal = ("QPushButton {\n"
"    background-color: rgb(17, 18, 17);\n"
"    border-radius:0px;\n"
"    border-top-right-radius:10px;\n"
"    margin:0px;   \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(232, 17, 35);\n"
"    border-radius:0px;\n"
"    border-top-right-radius:10px;\n"
"    border-color:none;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(149, 20, 30);\n"
"    border-radius:0px;\n"
"    border-top-right-radius:10px;\n"
"}\n"
"")
exit_button_stylesheet_window_maximized = ("QPushButton {\n"
"    background-color: rgb(17, 18, 17);\n"
"    border-radius:0px;\n"
"    border-top-right-radius:0px;\n"
"    margin:0px;   \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(232, 17, 35);\n"
"    border-radius:0px;\n"
"    border-top-right-radius:0px;\n"
"    border-color:none;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(149, 20, 30);\n"
"    border-radius:0px;\n"
"    border-top-right-radius:0px;\n"
"}\n"
"")
nav_frame_stylesheet = ("    background-color: rgb(25, 26, 25);\n"
"    border-radius: 0px;\n")
browser_tabs_stylesheet=("QTabBar::tab {\n"
"    font: 7.5pt \"Alice\";\n"
"    color: rgb(236, 236, 236);\n"
"    border-bottom: 1px;\n"
"    border-top: 0px;\n"
"    border-left: 0px;\n"
"    border-right: 0px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    border-style: solid;\n"
"    border-bottom-color:  rgb(25, 26, 25);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: None;\n"
"    background-color: rgb(42, 43, 42);\n"
"    color: rgb(236, 236, 236);\n"

"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    background-color: rgb(15, 16, 15);\n"
"    color: rgb(130, 130, 130);\n"

"}\n"
"\n"
"QTabBar::tab:!selected:hover {\n"
"    background-color: rgb(42,43,42);\n"

"}\n"
"\n"
"QTabBar::tab:top:!selected {\n"
"    margin-top: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected {\n"
"    margin-bottom: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:top, QTabBar::tab:bottom {\n"
"    min-width: 8px;\n"
"    margin-right: -1px;\n"
"    padding: 5px 10px 5px 10px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected {\n"
"    border-bottom-color: qlineargradient(spread:reflect, x1:0.488636, y1:0, x2:0, y2:0.00495455, stop:0 rgba(85, 40, 107, 255), stop:1 rgba(32, 33, 32, 255));\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected {\n"
"    border-top-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:top:last, QTabBar::tab:bottom:last,\n"
"QTabBar::tab:top:only-one, QTabBar::tab:bottom:only-one {\n"
"    margin-right: 0;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected {\n"
"    margin-right: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected {\n"
"    margin-left: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:left, QTabBar::tab:right {\n"
"    min-height: 8px;\n"
"    margin-bottom: -1px;\n"
"    padding: 10px 5px 10px 5px;\n"
"}\n"
"\n"
"QTabBar::tab:left:selected {\n"
"    border-left-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:right:selected {\n"
"    border-right-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:left:last, QTabBar::tab:right:last,\n"
"QTabBar::tab:left:only-one, QTabBar::tab:right:only-one {\n"
"    margin-bottom: 0;\n"
"}")
browser_tabs_add_button_stylesheet=("QPushButton {\n"
		"    background-color:rgb(42,43,42);\n"
		"    font: 20pt \"Alice\";\n"
		"    text-align: center;\n"
		"    color: rgb(236, 236, 236);\n"
		"    border:1px solid rgb(37,38,37);\n"
		"    border-radius:12px;\n"
		"}\n"
		"QPushButton:hover {\n"
		"    background-color:rgb(52,53,52);\n"
		"}\n"
		"QPushButton:pressed {\n"
		"    background-color:rgb(47,48,47);\n"
		"    border:2px solid rgb(30,31,30);\n"
		"}")
back_button_stylesheet = ("QPushButton {\n"
		"    background-color:rgb(42,43,42);\n"
		"    border:2px solid rgb(37,38,37);\n"
		"    border-radius:20px;\n"
		"}\n"
		"QPushButton:hover {\n"
		"    background-color:rgb(52,53,52);\n"
		"}\n"
		"QPushButton:pressed {\n"
		"    background-color:rgb(47,48,47);\n"
		"    border:2px solid rgb(30,31,30);\n"
		"    border-radius:20px;\n"
		"}")
foward_button_stylesheet = back_button_stylesheet
reload_button_stylesheet = ("QPushButton {\n"
		"    background-color:rgb(42,43,42);\n"
		"    border:2px solid rgb(37,38,37);\n"
		"    border-radius:17px;\n"
		"}\n"
		"QPushButton:hover {\n"
		"    background-color:rgb(52,53,52);\n"
		"}\n"
		"QPushButton:pressed {\n"
		"    background-color:rgb(47,48,47);\n"
		"    border:2px solid rgb(30,31,30);\n"
		"    border-radius:17px;\n"
		"}")
adress_line_edit_stylesheet = ("QLineEdit {\n"
		"    background-color: rgb(17, 18, 17);\n"
		"    border:2px solid;\n"
		"    border-color:rgb(42, 42, 42);\n"
		"    font: 10.5pt \"Alice\";\n"
		"    color: rgb(236, 236, 236);\n"
		"    border-radius:5px;\n"
		"    selection-background-color: rgb(85, 40, 107);\n"
		"}\n"
		"    QLineEdit:hover {\n"
		"    border: 2px solid;\n"
		"    border-color: rgb(65, 65, 65);\n"
		"    border-radius:5px;\n"
		"}\n"
		"    QLineEdit:focus {\n"
		"    border-radius:5px;\n"
		"    border-color:rgb(85, 40, 107);\n"
		"}\n"
		"    QLineEdit:focus:hover {\n"
		"    border-color: rgb(105, 60, 127);\n"
		"    border-radius:5px;\n"
		"}")
home_button_stylesheet = ("QPushButton {\n"
		"    background-color:rgb(42,43,42);\n"
		"    border:2px solid rgb(37,38,37);\n"
		"    border-radius:5px;\n"
		"}\n"
		"QPushButton:hover {\n"
		"    background-color:rgb(52,53,52);\n"
		"}\n"
		"QPushButton:pressed {\n"
		"    background-color:rgb(47,48,47);\n"
		"    border:2px solid rgb(30,31,30);\n"
		"    border-radius:5px;\n"
		"}")